name = "SimpleTraits"
uuid = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
author = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.9.2"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Markdown"]
